name: horus
channels:
  - pytorch
  - conda-forge
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
  - defaults
  - https://mirrors.ustc.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - absl-py=0.13.0=py38h06a4308_0
  - aiohttp=3.7.4.post0=py38h7f8727e_2
  - argon2-cffi=20.1.0=py38h27cfd23_1
  - async-timeout=3.0.1=py38h06a4308_0
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd8ed1ab_0
  - blinker=1.4=py38h06a4308_0
  - bottleneck=1.3.2=py38heb32a55_1
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.9.30=h06a4308_1
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2021.10.8=py38h06a4308_0
  - cffi=1.14.6=py38h400218f_0
  - chardet=4.0.0=py38h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.1=pyhd3eb1b0_0
  - coverage=5.5=py38h27cfd23_2
  - cryptography=3.4.8=py38hd23ed53_0
  - cudatoolkit=11.1.1=h6406543_8
  - cycler=0.10.0=py38_0
  - cython=0.29.24=py38h295c915_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.4.1=py38h709712a_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h0708190_1
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.69.1=h5202010_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.36.1=py38h2157cd5_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - importlib-metadata=4.8.1=py38h06a4308_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - ipykernel=6.4.2=py38he5a9106_0
  - ipython=7.28.0=py38he5a9106_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py38h578d9bd_2
  - jinja2=3.0.2=pyhd8ed1ab_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=4.1.2=pyhd8ed1ab_0
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_core=4.9.0=py38h578d9bd_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - kiwisolver=1.3.1=py38h2531618_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.17.2=h4ff587b_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.42.0=h7f98852_0
  - libwebp=1.2.0=h89dd481_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - markdown=3.3.4=py38h06a4308_0
  - markupsafe=2.0.1=py38h497a2fe_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py38h497a2fe_1004
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py38h497a2fe_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h1abd341_0
  - multidict=5.1.0=py38h27cfd23_2
  - munkres=1.1.4=py_0
  - nbclient=0.5.4=pyhd8ed1ab_0
  - nbconvert=6.2.0=py38h578d9bd_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - ninja=1.10.2=h4bd325d_0
  - notebook=6.4.5=pyha770c72_0
  - numexpr=2.7.3=py38h22e1b3c_1
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1l=h7f8727e_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandoc=2.15=h7f98852_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py38h5aabda8_0
  - pip=21.2.4=py38h06a4308_0
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.21=pyha770c72_0
  - protobuf=3.17.2=py38h295c915_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyjwt=2.1.0=py38h06a4308_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.17.3=py38h497a2fe_2
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.8.0=py3.8_cuda11.1_cudnn8.0.5_0
  - pytz=2021.3=pyhd3eb1b0_0
  - pyyaml=5.4.1=py38h27cfd23_1
  - pyzmq=19.0.2=py38ha71036d_2
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.7.1=py38h292c36d_2
  - seaborn=0.11.2=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=58.0.4=py38h06a4308_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=hc218d9a_0
  - tensorboard=2.6.0=py_1
  - tensorboard-data-server=0.6.0=py38hca6d32c_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - terminado=0.12.1=py38h578d9bd_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.8.0=py38
  - torchvision=0.9.0=py38_cu111
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.62.2=pyhd3eb1b0_1
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=2.0.1=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.6.3=py38h27cfd23_0
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - d2l==0.17.1
    - flatbuffers==2.0
    - graphsurgeon==0.4.5
    - idna==2.10
    - ipywidgets==7.6.5
    - joblib==1.1.0
    - jupyter==1.0.0
    - jupyter-console==6.4.0
    - jupyterlab-widgets==1.0.2
    - lxml==4.8.0
    - matplotlib==3.3.3
    - numpy==1.18.5
    - onnx==1.10.2
    - onnxruntime-gpu==1.10.0
    - pandas==1.2.2
    - py==1.11.0
    - qtconsole==5.2.2
    - qtpy==1.11.3
    - requests==2.25.1
    - scapy==2.4.3
    - scikit-learn==1.0.1
    - sklearn==0.0
    - tensorrt==8.2.1.8
    - thop==0.0.31-2005241907
    - threadpoolctl==3.0.0
    - uff==0.6.9
    - volksdep==3.2.0
    - widgetsnbextension==3.5.2
prefix: /home/wukaidong/anaconda3/envs/horus
